### ISSUE TITLE
Web service wrong ssl version

### ISSUE THREAD

**Issue by etrever** [VernissageApp/VernissageServer#148]
‘’’’
TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at a.invoke (file:///usr/local/app/dist/VernissageWeb/server/polyfills.server.mjs:3:6702)
    at m.run (file:///usr/local/app/dist/VernissageWeb/server/polyfills.server.mjs:3:1965)
    at file:///usr/local/app/dist/VernissageWeb/server/polyfills.server.mjs:4:577
    at a.invokeTask (file:///usr/local/app/dist/VernissageWeb/server/polyfills.server.mjs:3:7328)
    at m.runTask (file:///usr/local/app/dist/VernissageWeb/server/polyfills.server.mjs:3:2604)
    at O (file:///usr/local/app/dist/VernissageWeb/server/polyfills.server.mjs:3:9364)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: [Error: 803CD96EE77F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
‘’’’

**Comment by mczachurski** [comment]
Could you provide a bit more information about this issue? Specifically, when does this error occur, and what command or action triggers it?

**Comment by etrever** [comment]
I am trying to use the provided docker images, with Cloudflare in front for TLS and caching.    I will start my configuration from scratch again soon and update my tickets with more in depth detail.

**Comment by etrever** [comment]
We can close this one - it was likely due to my using nginx-proxy container instead of the proper vernissage-proxy one.
